name = "tellezlabs"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "tellezlabs-prod"
route = "tellezlabs.com/*"
zone_id = ""

[build]
command = ""
cwd = "./"
watch_paths = []

[build.upload]
format = "service-worker"
main = "./index.html"
